Ingenias 2025 Data Science 

In [ ]:
Ejercicios
1.Crear un arreglo de ceros de longitud 12
2.Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3.Crear un arreglo que tenga los números del 10 al 49
4.Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5.Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6.Calcular la media de un arreglo usando np.sum
7.Calcular la varianza de un arreglo usando np.sum y np.mean
8.Crear un array de números aleatorios usando np.random.randn.

In [1]:
#Importar numpy
import numpy as np

In [9]:
#Ejercicio 1

array_ceros = np.zeros(12)
print (array_ceros)
len (array_ceros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [15]:
#Ejercicio 2

array = np.zeros(10)
array [4] = 10
print (array)
len (array)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


10

In [17]:
#Ejercicio 3

array = np.arange(10,50)
print (array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
#Ejercicio 4

matriz = np.arange(9).reshape(3,3)
print (matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [81]:
#Ejercicio 5

#Crea un array de 100 numeros enteros aleatorios entre 0 y 50 
array_aleatorio = np.random.randint(0,50,size=100)
print (array_aleatorio)

[42 35 18 30  2  1 45 11 14  0  6 27 30  0  3 25 46  2  0 38 30 32 42 33
 27 24 33 47  3 41 23 30 26 13 32 25  6 24 48 23 40  2 18 35 40 47 39  4
 47  5 40  7 17 34 35  9  9 40 48  2  8 28  8  5 35  0  2 40 15  6 13 14
 32 30  7 39 49 31 25 43 19 27 39  1 32 44 13 30 14 35 29 31 31 28 30  1
  6 49  2  1]


In [83]:
#Obtiene la media del array
array_media = np.mean(array_aleatorio)
print (array_media)

23.47


In [75]:
#Obtiene la varianza del array
array_varianza = np.var(array_aleatorio)
print (array_varianza)

205.6931


In [77]:
#Ejercicio 6

#Calcula la suma de los elementos del array creado en el ejercicio anterior
array_suma = np.sum(array_aleatorio)
print (array_suma)

#Calcula el numero de elementos del array
num_elementos = array_aleatorio.size
print (num_elementos)

#Calcula la media
media = array_suma / num_elementos
print ("La media del arreglo:",media)


2463
100
La media del arreglo: 24.63


In [79]:
#Ejercicio 7

#Calcula la media del array
array_media = np.mean(array_aleatorio)
print (array_media)

#Calcula la suma de los cuadrados de las diferencias 
suma_cuadrados = np.sum((array_aleatorio - array_media) ** 2)
print (suma_cuadrados)

#Calcula el numero de elementos para varianza
num_elementos = array_aleatorio.size
print (num_elementos)

#Calcula varianza
varianza = suma_cuadrados / num_elementos
print ("La varianza es:",varianza)



24.63
20569.309999999998
100
La varianza es: 205.6931


In [87]:
#Ejercicio 8

array = np.random.rand(10)
print (array)


[0.88087051 0.46986933 0.38382733 0.03073332 0.95367384 0.31418978
 0.90375854 0.12716509 0.58474313 0.38080724]
